server:
  port: 8080

spring:
  application:
    name: jwt-validator

#prometeus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true