apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jwt-validation
  labels:
    app: jwt-validation
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    any: true
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 10s